@startuml
package client {
    component "web browser"
    component mobile

}

queue "Throughput limiter"

package Server {
    component "API SERVERS"
}



"web browser" -> "Throughput limiter"
"Throughput limiter" -> Server

@enduml
