@startuml
entity namespace {
id bigint
---
owner_id bigint
is_shared boolean
created_at timestamp
}

entity user {
user_id bigint
---
user_name varchar
created_at timestamp
}

entity block{
block_id bigint
---
file_version_id bigint
block_order int
}

entity device {
device_id uuid
---
user_id bigint
last_logged_in_at timestamp
}

entity file {
id bigint
---
file_name varchar
relative_path varchar
ios_directory boolean
latest_version bigint
checksum bigint
created_at timestamp
last_modified timestamp
}

entity file_version {
id bigint
---
file_id bigint
device_id uuid
version_number bigint
last_modified timestamp
}

namespace }o-left-|{user
user }|--o{device
namespace }|-right-o{file
file }--{file_version
block }o--|{file_version
device }|--|{file_version
@enduml