@startuml
autonumber
participant 클라이언트1
participant 클라이언트2
participant "블록 저장소 서버"
participant "클라우드 저장소"
participant "API 서버"
participant "메타데이터 DB"
participant "알림 서비스"
activate 클라이언트1
activate 클라이언트2
클라이언트1 -> "API 서버" : 파일 메타데이터 추가
activate "API 서버"

"API 서버" -> "메타데이터 DB" : 업로드 상태 : 대기중
activate "메타데이터 DB"
"메타데이터 DB" -> "알림 서비스" : 변경 발생 알림
activate "알림 서비스"
클라이언트2 <-- "알림 서비스" : 변경 발생 알림
activate "블록 저장소 서버"
클라이언트1 -> "블록 저장소 서버" : 파일 업로드
"블록 저장소 서버" -> "클라우드 저장소" : 파일 업로드
activate "클라우드 저장소"
"클라우드 저장소" -> "API 서버" : 메타데이터 갱신
deactivate "클라우드 저장소"
"API 서버" -> "메타데이터 DB" : 업로드 상태: 완료
deactivate "API 서버"
"메타데이터 DB" -> "알림 서비스" : 변경 발생 알림
deactivate "메타데이터 DB"
"클라이언트2" <-- "알림 서비스" : 변경 발생 알림

@enduml